### ISSUE TITLE
Adjust the content of the app to the font and screen size from the phone

### ISSUE THREAD

**Issue by TAriasVergara** [jcvasquezc/SMA2#151]
Whenever you choose the option "Large" in the font-size settings from the phone, all of the content from the app overlaps. 

This can be fixed using "LinearLayouts" in the layout files. 

I've already fixed most of the layout files, but I have not commit anything yet.

**Comment by TAriasVergara** [comment]
![issue](https://user-images.githubusercontent.com/29805969/47225123-9660b500-d3bd-11e8-8b40-a1eaab022004.png)

**Comment by PKlumpp** [comment]
What layout file is this? There are so many layout files that were all named profile.
For the settings screen: Of course it does not work if the RadioButton sizes are defined with discrete numbers. They should be ratios of screen width assigned with the constraint `app:layout_constraintWidth_percent`.

**Comment by TAriasVergara** [comment]
The file is called "activity_profile_xml".

Is not only the Radio buttons. TextViews and Buttons (in general) are also affected.

**Comment by PKlumpp** [comment]
Ok I see. The TextViews have wrap_content as width. And they are inside other linear layouts. there is a lot of mess going on in these Layout files.

**Comment by TAriasVergara** [comment]
Solved
