### ISSUE TITLE
Error in database.

### ISSUE THREAD

**Issue by lfelipeparra** [jcvasquezc/SMA2#160]
In my cellphone, the apkinson do not work. There is a SQLiteException. The error is:

android.database.sqlite.SQLiteException: no such table: EXERCISE (code 1): , while compiling: SELECT T."_id",T."NAME",T."EXERCISE_TYPE",T."SHORT_DESCRIPTION",T."SHORT_INSTRUCTIONS",T."INSTRUCTION_VIDEO_PATH",T."INSTRUCTION_TEXT_PATH",T."FRAGMENT_CLASS" FROM "EXERCISE" T

**Comment by nicanorgarcia** [comment]
When does this happen? Please run a Debug to identify the method in which this fails.

**Comment by nicanorgarcia** [comment]
This was happening because the device had a previous version of the database. We need to apply migrations if we make changes between release versions.

**Comment by nicanorgarcia** [comment]
I will close this issue and open a new one on the cause of the problem.
