### ISSUE TITLE
Remove GPL FFT implimentation

### ISSUE THREAD

**Issue by AKuederle** [jcvasquezc/SMA2#232]
The current version of an fft in `Speech/tools/FFT` and `Speech/tools/FourierTransform` is licenced under GPL. We should replace it with something with a more permissive licence.

Potential other versions: https://commons.apache.org/proper/commons-math/javadocs/api-3.4/org/apache/commons/math3/transform/FastFourierTransformer.html

**Comment by TAriasVergara** [comment]
Done #245
