### ISSUE TITLE
Update Instruction Page to show descriptions and text instructions

### ISSUE THREAD

**Issue by AKuederle** [jcvasquezc/SMA2#53]
We need some changes for the Instruction page.

- [x] Fix visuals
- [x] Fix Button Text
- [x] ShowShort instructions
- [x] Show short descriptions
- [x] actual show the long instructions

**Comment by TAriasVergara** [comment]
I'll do it. A text instruction fragment was already implemented, but i will do the pull request after the issues with the branches is solved
